package se.skltp.mb.intsvc;

/**
 * Error code enumeration for errors generated by {@link ReceiveMessagesImpl}.
 * <p/>
 * There are no expected errors that are interesting to the caller of ReceiveMessages, so we only
 * have one error. Support gets the real error reported in logs and alarm events.
 *
 * @author mats.olsson@callistaenterprise.se
 */
public enum ReceiveErrorCode {

    /**
     * Generic error.
     */
    MB0001("Technical error");

    private final String message;

    ReceiveErrorCode(String message) {
        this.message = message;
    }

    public String toString() {
        return name() + ":" + message;
    }

    public String getMessage() {
        return message;
    }
}
