package se.skltp.messagebox.intsvc;

/**
 * Error code enumeration for errors generated by {@link ReceiveMessagesImpl}.
 *
 * @author mats.olsson@callistaenterprise.se
 */
public enum ReceiveErrorCode {

    /**
     * Generic error.
     */
    MB0001("Technical error");

    private final String message;

    ReceiveErrorCode(String message) {
        this.message = message;
    }

    public String toString() {
        return name() + ":" + message;
    }

    public String getMessage() {
        return message;
    }
}
