/**
 * Copyright (C) 2013 Inera AB (http://www.inera.se)
 *
 * This file is part of Inera MessageService (http://code.google.com/p/inera-message).
 *
 * Inera MessageService is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Inera MessageService is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package se.skltp.messagebox.intsvc;

import java.lang.reflect.Field;
import java.util.Date;
import javax.servlet.http.HttpServletRequest;
import javax.xml.ws.WebServiceContext;
import javax.xml.ws.handler.MessageContext;

import org.junit.Before;
import org.mockito.Mock;
import se.skltp.messagebox.types.entity.MessageBody;
import se.skltp.messagebox.types.entity.MessageMeta;
import se.skltp.messagebox.types.entity.MessageStatus;
import se.skltp.messagebox.svc.services.MessageService;
import se.skltp.messagebox.types.services.TimeService;

import static org.mockito.Mockito.when;

/**
 * Base class for testing.
 *
 * Note: TimeService will by default be mocked-up to return a constant time.
 *
 * @author mats.olsson@callistaenterprise.se
 */
public class BaseTestImpl {
    @Mock
    MessageService messageService;
    @Mock
    WebServiceContext wsContext;
    @Mock
    MessageContext msgContext;
    @Mock
    HttpServletRequest servletRequest;
    @Mock
    TimeService timeService;

    protected String correlationId = "correlationId";

    @Before()
    public void onSetUp() {
        // setup the timeservice to run in fixed time
        long now = System.currentTimeMillis();
        when(timeService.now()).thenReturn(now);
        when(timeService.date()).thenReturn(new Date(now));
    }

    // needed to set the message id which is normally generated by the persistance layer
    public MessageMeta createMessage(long id, String targetSystem, String targetOrganization, String serviceContract, String messageText) throws NoSuchFieldException, IllegalAccessException {
        String docBody = "<?xml version='1.0' encoding='UTF-8'?> <body>" + messageText + "</body>";
        MessageBody body = new MessageBody(docBody);
        MessageMeta result = new MessageMeta("sourceId", targetSystem, targetOrganization, serviceContract, body, correlationId, MessageStatus.RECEIVED, timeService.date());
        Field field = result.getClass().getDeclaredField("id");
        field.setAccessible(true);
        field.set(result, id);
        return result;
    }
}
