package se.skltp.messagebox.services;

import java.lang.reflect.Field;
import javax.servlet.http.HttpServletRequest;
import javax.xml.ws.WebServiceContext;
import javax.xml.ws.handler.MessageContext;

import org.mockito.Mock;
import se.skltp.messagebox.core.entity.Message;
import se.skltp.messagebox.core.service.MessageService;

/**
 * Base class for testing.
 *
 * @author mats.olsson@callistaenterprise.se
 */
public class BaseTestImpl {
    @Mock
    MessageService messageService;
    @Mock
    WebServiceContext wsContext;
    @Mock
    MessageContext msgContext;
    @Mock
    HttpServletRequest servletRequest;

    // needed to set the message id which is normally generated by the persistance layer
    public static Message createMessage(long id, String receiverId, String targetOrganization, String serviceContract, String body) throws NoSuchFieldException, IllegalAccessException {
        Message result = new Message("sourceId", receiverId, targetOrganization, serviceContract, body, "correlationId");
        Field field = result.getClass().getDeclaredField("id");
        field.setAccessible(true);
        field.set(result, id);
        return result;
    }
}
